# This repository targets sbt 1.x only, don't get PRs bumping sbt to 2.x
updates.pin  = [
  { groupId = "org.slf4j", artifactId="slf4j-api", version = "1." },
  { groupId = "org.scala-sbt", artifactId = "sbt", version = "1." },
  { groupId = "org.scala-sbt", artifactId = "scripted-plugin", version = "1." },
  { groupId = "org.scala-sbt", artifactId = "librarymanagement-ivy", version = "1." }
]
