version = 3.11.0
align {
  preset = none
}
docstrings {
  style = Asterisk
  blankFirstLine = keep
  wrap = keep
}
indent {
  defnSite = 2
  infix.exemptScope = []
}
maxColumn = 120
newlines {
  source = keep
  avoidForSimpleOverflow = all
  inInterpolation = avoid
}
rewrite {
  trailingCommas.style = keep
}
runner {
  dialect = scala213
}
