# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
install:
  - cmd: mkdir C:\sbt
  - cmd: curl -Lo C:\sbt\sbt https://github.com/coursier/sbt-launcher/releases/download/v1.2.17/csbt
  - cmd: curl -Lo C:\sbt\sbt.bat https://github.com/coursier/sbt-launcher/releases/download/v1.2.17/csbt.bat
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=C:\sbt;%JAVA_HOME%\bin;%PATH%
  - cmd: SET JAVA_OPTS=-Xmx4g -Xss2m
  - git submodule update --init --recursive
test_script:
  - sbt ++2.12.7 sbt-shading/scripted
branches:
  only:
    - master
